name: Deploy AWS S3

on:
  workflow_call:

jobs:
  S3:
    runs-on: ubuntu-latest
    steps:
      - name: Baixa artefato de build
        uses: actions/download-artifact@v4.1.2
        with:
          name: api

      - name: Transfere arquivos de build para S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }} 
          SOURCE_DIR: './'
